CREATE TABLE CHARTER_OFFICER_PERSONAL (
    FILING_NUM TEXT,
    LAYOUT_CODE TEXT,
    ADDRESS1 TEXT,
    ADDRESS2 TEXT,
    CITY TEXT,
    STATE TEXT,
    ZIP_CODE TEXT,
    ZIP_EXTENSION TEXT,
    COUNTRY TEXT,
    OFFICER_ID NUMERIC,
    OFFICER_TITLE TEXT,
    LAST_NAME TEXT,
    FIRST_NAME TEXT,
    MIDDLE_NAME TEXT,
    SUFFIX TEXT
);
CREATE INDEX ON CHARTER_OFFICER_PERSONAL(FILING_NUM);