CREATE TABLE FILING_HIST (
    FILING_NUM INT PRIMARY KEY NOT NULL,
    LAYOUT_CODE INT NOT NULL,
    DOCUMENT_NUMBER INT,
    FILING_TYPE_ID INT,
    FILING_TYPE TEXT,
    ENTRY_DATE INT,
    FILING_DATE INT,
    EFFECTIVE_DATE INT,
    EFFECTIVE_COND_FLAG INT,
    INACTIVE_DATE INT
);