CREATE TABLE CHARTER_OFFICER_PERSONAL (
    FILING_NUM INT PRIMARY KEY NOT NULL,
    LAYOUT_CODE INT NOT NULL,
    ADDRESS1 TEXT,
    ADDRESS2 TEXT,
    CITY TEXT,
    STATE TEXT,
    ZIP_CODE TEXT,
    ZIP_EXTENSION TEXT,
    COUNTRY TEXT,
    OFFICER_ID INT,
    OFFICER_TITLE TEXT,
    LAST_NAME TEXT,
    FIRST_NAME TEXT,
    MIDDLE_NAME TEXT,
    SUFFIX TEXT
);