CREATE TABLE CHARTER_NAMES (
    FILING_NUM INT PRIMARY KEY NOT NULL,
    LAYOUT_CODE INT NOT NULL,
    NAME_ID INT,
    NAME TEXT,
    NAME_STATUS_ID INT,
    NAME_TYPE_ID INT,
    CREATION_DATE INT,
    INACTIVE_DATE INT,
    EXPIRE_DATE INT,
    COUNTY_TYPE TEXT,
    CONSENT_FILING_NUMBER INT,
    SELECTED_COUNTY_ARRAY TEXT,
    RESERVED TEXT
);