CREATE TABLE REGISTERED_AGENT_PERSONAL (
    FILING_NUM INT PRIMARY KEY NOT NULL,
    LAYOUT_CODE INT NOT NULL,
    ADDRESS1 TEXT,
    ADDRESS2 TEXT,
    CITY TEXT,
    STATE TEXT,
    ZIP_CODE TEXT,
    ZIP_EXTENSION TEXT,
    COUNTRY TEXT,
    INACTIVE_DATE INT,
    AGENT_LAST_NAME TEXT,
    AGENT_FIRST_NAME TEXT,
    AGENT_MIDDLE_NAME TEXT,
    AGENT_SUFFIX TEXT
);