CREATE TABLE ASSOCIATED_ENTITY (
    FILING_NUM INT PRIMARY KEY NOT NULL,
    LAYOUT_CODE INT NOT NULL,
    ASSOCIATED_ENTITY_ID INT,
    ASSOCIATED_ENTITY_NAME TEXT,
    ENTITY_FILING_NUMBER INT,
    ENTITY_FILING_DATE INT,
    JURISDICTION_COUNTRY TEXT,
    JURISDICTION_STATE TEXT,
    INACTIVE_DATE INT,
    CAPACITY_ID INT
);