CREATE TABLE TOTALS_LOG (
    LAYOUT_CODE INT PRIMARY KEY NOT NULL,
    ALL_9S INT,
    DATE_OF_RUN INT,
    COUNT_01 INT,
    COUNT_02 INT,
    COUNT_03 INT,
    COUNT_04 INT,
    COUNT_05 INT,
    COUNT_06 INT,
    COUNT_07 INT,
    COUNT_08 INT,
    COUNT_09 INT,
    COUNT_10 INT,
    COUNT_11 INT,
    COUNT_12 INT,
    COUNT_13 INT
);