CREATE TABLE ADDRESS (
    FILING_NUM INT PRIMARY KEY NOT NULL,
    LAYOUT_CODE INT NOT NULL,
    ADDRESS1 TEXT,
    ADDRESS2 TEXT,
    CITY TEXT,
    STATE TEXT,
    ZIP_CODE TEXT,
    ZIP_EXTENSION TEXT,
    COUNTRY TEXT
);