CREATE TABLE FILING_HIST (
    FILING_NUM TEXT,
    LAYOUT_CODE TEXT,
    DOCUMENT_NUMBER NUMERIC,
    FILING_TYPE_ID NUMERIC,
    FILING_TYPE TEXT,
    ENTRY_DATE DATE,
    FILING_DATE DATE,
    EFFECTIVE_DATE DATE,
    EFFECTIVE_COND_FLAG NUMERIC,
    INACTIVE_DATE DATE
);
CREATE INDEX ON FILING_HIST(FILING_NUM);