CREATE TABLE TOTALS_LOG (
    LAYOUT_CODE TEXT,
    ALL_9S NUMERIC,
    DATE_OF_RUN DATE,
    COUNT_01 NUMERIC,
    COUNT_02 NUMERIC,
    COUNT_03 NUMERIC,
    COUNT_04 NUMERIC,
    COUNT_05 NUMERIC,
    COUNT_06 NUMERIC,
    COUNT_07 NUMERIC,
    COUNT_08 NUMERIC,
    COUNT_09 NUMERIC,
    COUNT_10 NUMERIC,
    COUNT_11 NUMERIC,
    COUNT_12 NUMERIC,
    COUNT_13 NUMERIC
);