CREATE TABLE AUDIT_LOG (
    FILING_NUM INT PRIMARY KEY NOT NULL,
    LAYOUT_CODE INT NOT NULL,
    AUDIT_DATE INT,
    TABLE_ID INT,
    FIELD_ID INT,
    ACTION TEXT,
    CURRENT_VALUE TEXT,
    AUDIT_COMMENT TEXT
);